AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/**/*
    - vendor/**/*
    - spec/**/*
    - config/**/*
    - lib/**/*
    - node_modules/**/*
    - Rakefile
    # - tmp/localtime.rb
    # - Guardfile
  TargetRubyVersion: 2.5
# Metrics/AbcSize:
#   Max: 22
# Metrics/BlockLength:
#   Max: 86
# Metrics/LineLength:
#   Max: 141
# Metrics/MethodLength:
#   Max: 23
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_training.yml
