# Rubocop詳細設定
Metrics/AbcSize:
  Max: 70

Metrics/BlockLength:
  Max: 400
  Exclude:

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 230

Metrics/MethodLength:
  Max: 40
  Exclude:

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    # - staging

Rails/ApplicationRecord:
  Description: 'Check that models subclass ApplicationRecord.'
  Enabled: false

# 不要なものはEnabled: falseで設定を除外する

# Rails/HasManyOrHasOneDependent:
#   Enabled: false
#
# Style/ClassAndModuleChildren:
#   Enabled: false
#
# Naming/VariableNumber:
#   Enabled: false
#
# Style/FrozenStringLiteralComment:
#   Enabled: false
#
# Style/SafeNavigation:
#   Enabled: false
#
# Style/NumericPredicate:
#   Enabled: false
#
# Performance/RegexpMatch:
#   Enabled: false
